oam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls'))
]

videos/urls.py
from django.urls import path

from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('v/<int:pk>', views.VideoDetailView.as_view(), name='video_detail'),
]

videos/models.py
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Video(models.Model):
    title = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='videos')
    description = models.TextField(blank=True)
    youtubeId = models.CharField(max_length=11)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.artist}: {self.title}'

videos/views.py
from django.views import generic

from videos.models import Video


class IndexView(generic.ListView):
    # TODO: only latest videos
    template_name = 'videos/index.html'
    queryset = Video.objects.order_by('-added_on')


class VideoDetailView(generic.DetailView):
    model = Video

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_videos'] = Video.objects.exclude(id=self.object.id).order_by('-added_on')
        return context

videos/templates/videos/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <title>
        {% block title %}
        {% endblock %}
        - OpenAfgMusic
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'videos:index' %}"><img src="{% static 'img/logo-large.png' %}" height="30"
                                                                 alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Videos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">MP3s</a>
            </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

videos/templates/videos/index.html
{% extends 'videos/base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div id="carouselExampleIndicators" class="jumbotron carousel carousel-fade slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            {% for video in video_list|slice:":3" %}
                <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                    <a href="{% url 'videos:video_detail' video.id %}">
                        <img class="d-block w-100"
                             src="https://img.youtube.com/vi/{{ video.youtubeId }}/maxresdefault.jpg"
                             alt="{{ video.artist }}: {{ video.title }}">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ video.title }}</h5>
                            <p>{{ video.artist }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <h4>Songs</h4>
    <div class="row song-collection">
        {% for video in video_list %}
            <div class="col-4 col-md-3 col-lg-2 song-card">
                <a href="{% url 'videos:video_detail' video.id %}">
                    <div class="card">
                        <img class="card-img-top" src="https://img.youtube.com/vi/{{ video.youtubeId }}/mqdefault.jpg"
                             alt="{{ video.artist }}: {{ video.title }}">
                        <div class="card-body song-card-text">
                            <h5 class="card-title song-card-artist">{{ video.artist }}</h5>
                            <p class="card-subtitle song-card-title">{{ video.title }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

videos/templates/videos/video_detail.html
{% extends 'videos/base.html' %}

{% block title %}
    {{ video.artist }}: {{ video.title }}
{% endblock %}

{% block content %}
    <div class="card">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item"
                    src="https://www.youtube-nocookie.com/embed/{{ video.youtubeId }}?rel=0&amp;modestbranding=1"
                    allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <div class="card-body main-song-text">
            <h5 class="card-title">
                {{ video.artist }}: {{ video.title }}
            </h5>
            <p class="card-text">
                {{ video.description|linebreaksbr }}
            </p>
        </div>
    </div>

    <h4>More videos</h4>
    <div class="row song-collection">
        {% for v in related_videos %}
            <div class="col-4 col-md-3 col-lg-2 song-card">
                <div class="card">
                    <a href="{% url 'videos:video_detail' v.id %}">
                        <img class="card-img-top" src="https://img.youtube.com/vi/{{ v.youtubeId }}/mqdefault.jpg"
                             alt="{{ v.artist }}: {{ v.title }}">
                        <div class="card-body song-card-text">
                            <h5 class="card-title song-card-artist">{{ v.artist }}</h5>
                            <p class="card-subtitle song-card-title">{{ v.title }}</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}